shell script formatting

diff --git a/Client/proxy-config b/Client/proxy-config
--- a/Client/proxy-config
+++ b/Client/proxy-config
@@ -8,44 +8,50 @@
 # See https://github.com/BlueSkyTools/BlueSkyConnect
 # Licensed under the Apache License, Version 2.0
 
-usage () {
-	echo 'Usage: proxy-config [-h] [-s]
-	-h:	 HTTP Proxy Settings
-	-s:	 HTTPS Proxy Settings'
-	exit 255
+usage() {
+  cat << EOM
+Usage: proxy-config [-h] [-s]
+-h: HTTP Proxy Settings
+-s: HTTPS Proxy Settings
+EOM
+  exit 255
 }
 
-# get proxy info from system preferences
+# get proxy info from System Preferences
 # Detect active network service for active route
-routeServiceGUID=$(printf "open\nget State:/Network/Global/IPv4\nd.show" | scutil | grep "PrimaryService" | awk '{print $3}')
-routeServiceName=$(printf "open\nget Setup:/Network/Service/$routeServiceGUID\nd.show" | scutil | grep "UserDefinedName" | awk -F': ' '{print $2}')
+ROUTE_SERVICE_GUID=$(scutil <<< "show State:/Network/Global/IPv4" | awk -F " : " '/PrimaryService/ {print $2}')
+ROUTE_SERVICE_NAME=$(scutil <<< "show Setup:/Network/Service/$ROUTE_SERVICE_GUID" | awk -F " : " '/UserDefinedName/ {print $2}')
 
-## Arg parsing, for http or https settings
-arg="$1"
-case "$arg" in
-	-h)
-		networkSetupType='getwebproxy'
-		;;
-	-s)
-		networkSetupType='getsecurewebproxy'
-		;;
-	*)
-		usage
-		;;
-esac
+# Arg parsing, for HTTP or HTTPS settings
+while getopts ":hs" OPT; do
+  case $OPT in
+    h)
+      NETWORK_SETUP_TYPE="getwebproxy"
+      ;;
+    s)
+      NETWORK_SETUP_TYPE="getsecurewebproxy"
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG"
+      usage
+      ;;
+    *)
+      usage
+      ;;
+  esac
+done
 
-
-# Get details on proxy settings. This can take some time so lets only ask the system once.
-proxyDetails=$(networksetup -"$networkSetupType" "$routeServiceName")
+# Get details on proxy settings. This can take some time so let’s only ask the system once.
+PROXY_DETAILS=$(networksetup "-$NETWORK_SETUP_TYPE" "$ROUTE_SERVICE_NAME")
 # Are the proxy settings enabled?
-if [[ $(echo "$proxyDetails" | grep ^'Enabled: Yes') ]]; then
-	# It is enabled, lets read the data
-	proxyHostName=$(echo "$proxyDetails" | grep ^'Server:' | awk -F ': ' '{print $NF}')
-	proxyPort=$(echo "$proxyDetails" | grep ^'Port:' | awk -F ': ' '{print $NF}')
-	# sanity check, did we get those? A blank field for port in the GUI gives us an output string of "0", which is equally bad as null
-	if [[ -n $proxyHostName ]] && [[ -n $proxyPort ]] && [[ $proxyPort -ne 0 ]]; then
-		echo "http://$proxyHostName:$proxyPort"
-	fi
+if grep -q ^"Enabled: Yes" <<< "$PROXY_DETAILS"; then
+  # It is enabled, let’s read the data
+  PROXY_HOST_NAME=$(awk -F ": " '/^Server:/ {print $NF}' <<< "$PROXY_DETAILS")
+  PROXY_PORT=$(awk -F ": " '/^Port:/ {print $NF}' <<< "$PROXY_DETAILS")
+  # sanity check, did we get those? A blank field for port in the GUI gives us an output string of "0", which is equally bad as null
+  if [[ $PROXY_HOST_NAME ]] && [[ $PROXY_PORT ]] && [[ $PROXY_PORT -ne 0 ]]; then
+    echo "http://$PROXY_HOST_NAME:$PROXY_PORT" # should this be https if [[ $NETWORK_SETUP_TYPE = "getsecurewebproxy" ]] ?
+  fi
 fi
 
 exit 0
diff --git a/docker/run b/docker/run
--- a/docker/run
+++ b/docker/run
@@ -6,41 +6,35 @@
 
 # set mysql admin password
 if [[ $MYSQLROOTPASS ]]; then
-  mysqlRootPass=$MYSQLROOTPASS
+  MYSQL_ROOT_PASS=$MYSQLROOTPASS
+elif [[ $DB_ENV_MYSQL_ROOT_PASSWORD ]]; then
+  # let’s check for the linked container’s password
+  MYSQL_ROOT_PASS=$DB_ENV_MYSQL_ROOT_PASSWORD
 else
-	# lets check for the linked containers password
-	if [[ $DB_ENV_MYSQL_ROOT_PASSWORD ]]; then
-		mysqlRootPass=$DB_ENV_MYSQL_ROOT_PASSWORD
-	else
-		mysqlRootPass="admin"
-	fi
+  MYSQL_ROOT_PASS="admin"
 fi
 
 # wait for database
 COUNT=0
-while [ $COUNT -le 30 ]
-do
-	sleep 1;
-	COUNT=$((COUNT+1));
-
-  MYSQL_IS_RUNNING=$(mysqladmin -h db -u root -p'$mysqlRootPass' status 2>1 /dev/null | grep Uptime)
-
-  if [[ -z $MYSQL_IS_RUNNING ]]; then
-    if [ $COUNT -gt 60 ]; then
-      echo "We failed to connect to the database, exiting..."
-      exit 1;
+while [[ $COUNT -le 30 ]]; do
+  sleep 1
+  ((COUNT++))
+  if ! mysqladmin -h db -u root -p "$MYSQL_ROOT_PASS" status 2> /dev/null | grep -q Uptime; then
+    if [[ $COUNT -gt 60 ]]; then
+      echo "We failed to connect to the database. Exiting..."
+      exit 1
     fi
-    echo "Waiting for the database to start.  Attempt $COUNT..."
+    echo "Waiting for the database to start. Attempt $COUNT..."
   else
     echo "Database is running..."
     break
   fi
 done
 
-# run bluesky server config
+# run BlueSky server config
 /usr/local/bin/BlueSkyConnect/Server/server-config.sh
 
-# purge hanging sockets/pids
+# purge hanging sockets/PIDs
 rm -f /var/run/fail2ban/*
 
 # create and set perms for www/.ssh
@@ -51,18 +45,18 @@ chown www-data /var/www/.ssh
 chmod +r /certs/blueskyadmin.key
 chmod +r /certs/blueskyclient.key
 
-# set default bluesky user
-if [[ ! -z $DEFAULT_USER ]]; then
-	echo "$DEFAULT_USER" > /usr/local/bin/BlueSkyConnect/Server/defaultLogin.txt
+# set default BlueSky user
+if [[ $DEFAULT_USER ]]; then
+  echo "$DEFAULT_USER" > /usr/local/bin/BlueSkyConnect/Server/defaultLogin.txt
 fi
 
-# migrate ssh wrapper path for existing keys
-if [ ! -e /home/admin/.ssh/.authorized_keys_migrated ]; then
-  sed -i "s/bin\/BlueSky\/Server/bin\/BlueSkyConnect\/Server/g" /home/admin/.ssh/authorized_keys
+# migrate SSH wrapper path for existing keys
+if [[ ! -e /home/admin/.ssh/.authorized_keys_migrated ]]; then
+  sed -i "s|bin/BlueSky/Server|bin/BlueSkyConnect/Server|g" /home/admin/.ssh/authorized_keys
   touch /home/admin/.ssh/.authorized_keys_migrated
 fi
-if [ ! -e /home/bluesky/.ssh/.authorized_keys_migrated ]; then
-  sed -i "s/bin\/BlueSky\/Server/bin\/BlueSkyConnect\/Server/g" /home/bluesky/.ssh/authorized_keys
+if [[ ! -e /home/bluesky/.ssh/.authorized_keys_migrated ]]; then
+  sed -i "s|bin/BlueSky/Server|bin/BlueSkyConnect/Server|g" /home/bluesky/.ssh/authorized_keys
   touch /home/bluesky/.ssh/.authorized_keys_migrated
 fi
 
